//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyWebSql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_child
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public items_child()
        {
            this.baskets = new HashSet<basket>();
            this.images = new HashSet<image>();
            this.wish_list = new HashSet<wish_list>();
            this.order_items = new HashSet<order_items>();
            this.User_Comment = new HashSet<User_Comment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Stars { get; set; }
        public Nullable<int> VatId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PresentLess { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> Count { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public Nullable<double> ShippingPrice { get; set; }
        public Nullable<short> Status { get; set; }
        public string ShippingDescription { get; set; }
        public string ReturnDescription { get; set; }
        public string TimeShipping { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UnitsStock { get; set; }
        public Nullable<int> SizeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<basket> baskets { get; set; }
        public virtual color color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
        public virtual item item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wish_list> wish_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual size size { get; set; }
        public virtual vat vat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Comment> User_Comment { get; set; }
    }
}
