//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyWebSql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.Features = new HashSet<Feature>();
            this.order_items = new HashSet<order_items>();
            this.Tags = new HashSet<Tag>();
            this.User_Comment = new HashSet<User_Comment>();
            this.images = new HashSet<image>();
        }
    
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> Availablity { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CategoryType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Popular { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Type { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        public virtual category category1 { get; set; }
        public virtual collaborationData collaborationData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feature> Features { get; set; }
        public virtual image image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Comment> User_Comment { get; set; }
        public virtual site site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
    }
}
