//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyWebSql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.item_features = new HashSet<item_features>();
            this.items_child = new HashSet<items_child>();
            this.sub_categories = new HashSet<sub_categories>();
        }
    
        public int Id { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_features> item_features { get; set; }
        public virtual manufacturer manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<items_child> items_child { get; set; }
        public virtual site site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_categories> sub_categories { get; set; }
    }
}
